# Generated by Django 2.2 on 2020-03-17 16:23

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casino_supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('bonus', django_bleach.models.BleachField(blank=True, null=True)),
                ('link', django_bleach.models.BleachField(blank=True, null=True)),
                ('warning_label', django_bleach.models.BleachField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, default=500)),
            ],
        ),
    ]
