# Generated by Django 2.2 on 2020-03-18 08:59

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('intro_text', django_bleach.models.BleachField(blank=True)),
                ('content', django_bleach.models.BleachField(blank=True)),
                ('link', django_bleach.models.BleachField(blank=True)),
                ('date', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
