# Generated by Django 2.2 on 2020-03-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='automated_date',
            field=models.DateTimeField(auto_now_add=True, default='2020-03-18 11:05'),
            preserve_default=False,
        ),
    ]
